[project]
name = "rangoonx"
version = "0.1.0"
description = "This is static site"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Lynn Myat Aung", email = "rangoonx.com@gmail.com" }
]
dependencies = [
    "flet[all]>=1.0.0",
    "python-dotenv>=1.2.2",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.flet]
org = "com.RangoonX"
product = "RangoonX"
company = "RangoonX"
copyright = "Copyright (C) 2023-2026 by Flet"

[tool.flet.app]
path = "src"
